ch_2/site/config/routes.rb
FtwLawnCare::Application.routes.draw do
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }
  devise_scope :admin do
    get '/admin/sign_in',  :to => 'admins/home#index', :as => :new_admin_session
    get '/admin/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  devise_for :users

  namespace :admins do
    get '/',          :to => 'home#index'
    get '/dashboard', :to => 'home#index'
    get '/queue',     :to => 'queue#index'

    resources :admins, :only => [:index, :show]
    resources :logs,   :only => :index
    resources :users do
      post 'confirm',             :on => :member
      post 'impersonate',         :on => :member
      post 'resend_confirmation', :on => :member
      post 'reset_password',      :on => :member
    end
  end

  namespace :chargify do
    get '/callbacks/signup',         :to => 'callbacks#signup'
    get '/callbacks/account_update', :to => 'callbacks#account_update'
  end

  root :to => "home#index"
  get '/terms', :to => 'home#terms'
  get '/privacy', :to => 'home#privacy'
  get '/goodbye_world', :to => 'application#goodbye_world'
end

ch_2/site/app/views/layouts/_footer.html.haml
%footer
  .container
    .row
      .col-md-4
        %h4 FTW Lawn Care
        %p &copy; 2013 FTW Lawn Care.  All Rights Reserved.
      .col-md-4
        %h4 All Your Lawns Are Belong To Us
        %p And we'll take really good care of them.
      .col-md-4
        %h4 Helpful links:
        %ul
          %li
            = link_to 'Privacy policy', 'privacy'
          %li
            = link_to 'Terms of service', 'terms'

ch_2/site/app/views/layouts/_nav_bar.html.haml
%nav.navbar.navbar-default{:role=>'navigation'}
  .navbar-header
    %button.navbar-toggle{:type=>'button',:data => {:toggle=>'collapse',:target=>'.navbar-ex1-collapse'}}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{:href=>'/'}
      FTW Lawn Care

  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav
      %li
        %a{:href=>'/about'} About
      %li
        %a{:href=>'/feedback'} Feedback

ch_2/site/app/views/layouts/_the_flash.html.haml
- if flash[:notice]
  %p.alert.alert-success= flash[:notice]
- if flash[:alert]
  %p.alert.alert-danger= flash[:alert]

ch_2/site/app/views/layouts/admin.html.haml
!!!
%html
  %head
    %title Admin
    %meta{:name => 'viewport', :content => 'width=device-width, initial-scale=1.0'}
    %link{ :rel => 'shortcut icon', :href => "/images/favicon.ico", :type => "image/x-icon"}
    = stylesheet_link_tag 'admin'
    = csrf_meta_tags

  %body{:class => I18n.locale.to_s}
    %nav.navbar.navbar-inverse
      .container
        %button.navbar-toggle{"data-target" => ".bs-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "Admin", '/admins', :class => 'navbar-brand'
        .nav-collapse.collapse.bs-navbar-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Users', admins_users_path
        %p.navbar-text.pull-right
          - if current_admin
            = current_admin.email
            = link_to '(Logout)', destroy_admin_session_path
          - else
            = link_to 'Login', admin_omniauth_authorize_path(:google_oauth2)
    .container#main_wrapper
      .row
        - if current_admin
          .col-md-3
            %ul.nav.nav-pills.nav-stacked
              %li{:class => @top_nav == 'users' && 'active'}
                = link_to admins_users_path do
                  %span.glyphicon.glyphicon-user
                  Users
              %li{:class => @top_nav == 'admins' && 'active'}
                = link_to admins_admins_path do
                  %span.glyphicon.glyphicon-tower
                  Admins
              %li{:class => @top_nav == 'logs' && 'active'}
                = link_to '/admins/logs' do
                  %span.glyphicon.glyphicon-list-alt
                  Logs
              %li{:class => @top_nav == 'queue' && 'active'}
                = link_to '/admins/queue' do
                  %span.glyphicon.glyphicon-wrench
                  Queue
            %hr

            .row
              .col-xs-12
                Total users:
                %span.text-success= User.count

            %hr 

            .row
              .col-xs-12
                = render :partial => 'shared/masquerade'

              
          .col-md-9
            #main
              = render 'layouts/the_flash'
              = yield
        - else # The admin is not logged in
          .col-md-12
            = yield

    %script{:src => 'http://code.jquery.com/jquery.js', :type => 'text/javascript'}
    = javascript_include_tag 'application'
    = yield :additional_js

ch_2/site/app/views/layouts/application.html.haml
!!!5
%html
  %head
  %title FtwLawnCare
  = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
  = csrf_meta_tags
%body
  = render 'shared/masquerade'
  = render 'layouts/nav_bar'
  .content
    .container
      = render 'shared/flash_messages'
      = yield
  = render 'layouts/footer'

  %script{:src => 'http://code.jquery.com/jquery.js', :type => 'text/javascript'}
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = yield :additional_js