ch_4/site/config/routes.rb
FtwLawnCare::Application.routes.draw do
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }
  devise_scope :admin do
    get '/admin/sign_in',  :to => 'admins/home#index', :as => :new_admin_session
    get '/admin/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_admin_session
  end

  devise_for :users, :controllers => {:registrations => 'registrations'}

  namespace :admins do
    get '/',          :to => 'home#index'
    get '/dashboard', :to => 'home#index'
    get '/queue',     :to => 'queue#index'

    resources :admins, :only => [:index, :show]
    resources :logs,   :only => :index
    resources :users do
      post 'confirm',             :on => :member
      post 'impersonate',         :on => :member
      post 'resend_confirmation', :on => :member
      post 'reset_password',      :on => :member
    end
  end

  namespace :chargify do
    get '/callbacks/signup',         :to => 'callbacks#signup'
    get '/callbacks/account_update', :to => 'callbacks#account_update'
  end

  root :to => "home#index"
  get '/terms', :to => 'home#terms'
  get '/privacy', :to => 'home#privacy'
  get '/goodbye_world', :to => 'application#goodbye_world'
  get '/dashboard', :to => 'home#dashboard'
end

ch_4/site/app/views/admins/admins/_admin.html.haml
%tr
  %td= admin.id
  %td= admin.email
  %td
    - if admin.last_sign_in_at.nil? 
      %span.text-muted (never)
    - else 
      = admin.last_sign_in_at.to_s(:admin_date)
  %td
    = link_to admins_admin_path(:id => admin), :title => 'View' do
      %span.glyphicon.glyphicon-info-sign

ch_4/site/app/views/admins/admins/index.html.haml
.row
  .col-xs-12
    %h1 Admins

.row
  .col-xs-12
    = paginate @admins

    %table.table.table-condensed.table-striped
      %thead
        %tr 
          %th ID
          %th Email
          %th Last Sign In
          %th &nbsp;
      %tbody
        = render :partial => 'admin', :collection => @admins

    = paginate @admins

ch_4/site/app/views/admins/admins/show.html.haml
- content_for :additional_js do
  :javascript
    $('#user_nav a:first').tab("show")

%h1
  %span.glyphicon.glyphicon-tower
  = @admin.email

.row
  .col-xs-12
    #history.tab-pane
      .row
        .col-xs-12
          .page-header
            %h3 History
      .row
        .col-xs-12
          = render :partial => 'admins/logs/logs', :locals => {:logs => @logs}