ch_2/site/config/routes.rb
FtwLawnCare::Application.routes.draw do
  devise_for :admins, :controllers => { :omniauth_callbacks => "admins/omniauth_callbacks" }
  devise_scope :admin do
    get '/admin/sign_in',  :to => 'admins/home#index', :as => :new_admin_session
    get '/admin/sign_out', :to => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  devise_for :users

  namespace :admins do
    get '/',          :to => 'home#index'
    get '/dashboard', :to => 'home#index'
    get '/queue',     :to => 'queue#index'

    resources :admins, :only => [:index, :show]
    resources :logs,   :only => :index
    resources :users do
      post 'confirm',             :on => :member
      post 'impersonate',         :on => :member
      post 'resend_confirmation', :on => :member
      post 'reset_password',      :on => :member
    end
  end

  namespace :chargify do
    get '/callbacks/signup',         :to => 'callbacks#signup'
    get '/callbacks/account_update', :to => 'callbacks#account_update'
  end

  root :to => "home#index"
  get '/terms', :to => 'home#terms'
  get '/privacy', :to => 'home#privacy'
  get '/goodbye_world', :to => 'application#goodbye_world'
end

ch_2/site/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :async
end

ch_2/site/app/controllers/admins/users_controller.rb
module Admins
  class UsersController < AdminsRootController
    before_filter :set_nav

    def index
      command = Admin::SearchUsers.new(params[:user_search])

      @users = 
        if !command.execute
          command.results.order(:email).page params[:page]
        else
          flash.now[:notice] = "There was a problem with your search."
          []
        end
    end

    def show
      @user = User.find(params[:id])
    end

    def impersonate
      sign_in(:user, User.find(params[:id]), { :bypass => true })
      Log.masquerade(current_admin.id,params[:id])
      redirect_to '/'
    end

    # This is for resending the confirmation instructions.  Sometimes these get lost.
    def resend_confirmation
      @user = User.find(params[:id])
      @user.resend_confirmation_instructions
      Log.resent_confirmation(current_admin.id,@user.id)
      flash[:notice] = "Confirmation instructions resent."
      redirect_to admins_user_path(:id => @user.id)
    end

    def confirm
      @user = User.find(params[:id])
      @user.confirm!
      Log.confirmed_user(current_admin.id,@user.id)
      flash[:notice] = "User confirmed."
      redirect_to admins_user_path(:id => @user.id)
    end

    def reset_password
      @user = User.find(params[:id])
      @user.send_reset_password_instructions
      Log.reset_password(current_admin.id,@user.id)
      flash[:notice] = "Password reset instructions sent."
      redirect_to admins_user_path(:id => @user.id)
    end

    private

    def set_nav
      @top_nav = 'users'
    end
  end
end

ch_2/site/app/views/admins/users/_user.html.haml
%tr
  %td= user.id
  %td= user.email
  %td
    - if user.confirmed_at.nil?
      %span.text-danger.glyphicon.glyphicon-thumbs-down
    - else
      %span.text-success.glyphicon.glyphicon-thumbs-up
  %td
    - if user.last_sign_in_at.nil? 
      %span.text-muted (never)
    - else 
      = user.last_sign_in_at.to_s(:admin_date)
  %td
    = link_to admins_user_path(:id => user), :title => 'View' do
      %span.glyphicon.glyphicon-info-sign

ch_2/site/app/views/admins/users/index.html.haml
.row
  .col-xs-12
    %h1 Users

.row
  .col-xs-12
    .panel.panel-default
      .panel-heading Search
      .panel-body
        %form.form-inline{:action => admins_users_path, :method => :get}
          .form-group
            %label.sr-only{:for => 'user_search_email'} Search users by email
            .input-group
              %span.input-group-addon
                %span.glyphicon.glyphicon-envelope
              %input#user_search_email.form-control{:type => 'email', :placeholder => 'Search users by email', :name => 'user_search[email]', :value => params[:user_search].try(:[], :email)}
          - if params[:user_search]
            = link_to 'clear', admins_users_path

.row
  .col-xs-12
    = paginate @users

    %table.table.table-condensed.table-striped
      %thead
        %tr 
          %th ID
          %th Email
          %th Confirmed?
          %th Last Sign In
          %th &nbsp;
      %tbody
        = render :partial => 'user', :collection => @users

    = paginate @users

ch_2/site/app/views/admins/users/show.html.haml
- content_for :additional_js do
  :javascript
    $('#user_nav a:first').tab("show")

%h1= @user.email

.row
  .col-xs-12
    .well
      = link_to impersonate_admins_user_path(:id => @user.id), :class => 'btn btn-primary', :method => :post do
        %span.glyphicon.glyphicon-eye-open
        Masquerade as this user
      - if @user.confirmed?
        = link_to reset_password_admins_user_path(:id => @user.id), :class => 'btn btn-primary', :method => :post do
          %span.glyphicon.glyphicon-random
          Reset password
      - else
        = link_to resend_confirmation_admins_user_path(:id => @user.id), :class => 'btn btn-primary', :method => :post do
          %span.glyphicon.glyphicon-send
          Resend confirmation

.row
  .col-xs-12
    %ul.nav.nav-tabs#user_nav
      %li.active
        %a{:href => '#info',  :data => {:toggle=>'tab'}} Info
      %li
        %a{:href => '#history', :data => {:toggle=>'tab'}} History

.row
  .col-xs-12
    .tab-content
      #info.tab-pane.active
        .row
          .col-xs-12
            .page-header
              %h3 Info
        .row
          .col-xs.12
            %table.table.table-condensed.table-striped
              %tbody
                %tr
                  %th ID
                  %td= @user.id
                %tr
                  %th Email
                  %td= @user.email
                %tr
                  %th Confirmed?
                  %td
                    - if @user.confirmed_at.nil?
                      %span.text-danger.glyphicon.glyphicon-thumbs-down
                      = link_to confirm_admins_user_path(:id => @user.id), :class => 'btn btn-primary', :method => :post do
                        %span.glyphicon.glyphicon-thumbs-up
                        Confirm user
                    - else
                      %span.text-success.glyphicon.glyphicon-thumbs-up
                      = @user.confirmed_at.to_s(:admin_date)
                %tr
                  %th Last sign in
                  %td= @user.last_sign_in_at.try(:to_s, :admin_date)
      #history.tab-pane
        .row
          .col-xs-12
            .page-header
              %h3 History
        .row
          .col-xs-12
            %p.alert.alert-info
              %span.glyphicon.glyphicon-bullhorn
              Coming soon!